output_path: "./outputs"
white_bg: False
gaussian_path: "./screw_filled.ply"
gaussian_orig: "./3dgs_screw.ply"
lora_path: "./model/zxy_train2_5e5"

lrs:
    means: 1.6e-4
    scales: 1.0e-3
    quats: 1.0e-3
    opacities: 1.0e-2
    colors: 2.5e-3

sd_model_vertical: "sd2-community/stable-diffusion-2-depth"
sd_model_horizontal: "sd2-community/stable-diffusion-2-depth"

vertical_prompt: "a macro photo of the vertical cross section of a zxy screw"
vertical_negative_prompt: "low resolution, blurry, distorted, background, environment, full whole object, uncut, organic, soft, shadow"

horizontal_prompt: "a macro photo of the horizontal cross section of a zxy screw"
horizontal_negative_prompt: "low resolution, blurry, distorted, background, environment, full whole object, uncut, organic, soft, shadow"

sds_per_epoch: 10
sds_steps: 15
guidance_scale: 15
epochs: 400
init_radius: 0.3
